apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vault-kubernetes-role-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: tanuu.fi/v1
    resource: vaultkubernetesroles
  hooks:
    sync:
      webhook:
        url: http://vault-controller.vault/sync-kubernetes-role
    finalize:
      webhook:
        url: http://vault-controller.vault/sync-kubernetes-role
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: vault-policy-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: tanuu.fi/v1
    resource: vaultpolicies
  hooks:
    sync:
      webhook:
        url: http://vault-controller.vault/sync-policy
    finalize:
      webhook:
        url: http://vault-controller.vault/sync-policy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-controller
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-controller
  template:
    metadata:
      labels:
        app: vault-controller
    spec:
      # @TODO: Uncomment if needed
      # imagePullSecrets:
      # - name: regcred
      containers:
      - name: controller
        image: # @TODO: Add me!
        env:
        - name: VAULT_ADDR
          value: http://vault.vault.svc.cluster.local:8200
        - name: VAULT_KUBERNETES_ROLE
          value: platform-vault-controller
---
apiVersion: v1
kind: Service
metadata:
  name: vault-controller
  namespace: vault
spec:
  selector:
    app: vault-controller
  ports:
  - port: 80
